pipeline:
  build:
    image: klakegg/hugo:ext-alpine-ci
    commands:
      - hugo
      - rm -rf /site/*
      - mv -f public/* /site
    volumes:
      - /var/www/sites/facebook.tracking.exposed:/site

branches: 
  - master
